In [ ]:
# 1. Посмотрите видео Дэвида Бизли про всроенные инструменты Python
# 2. Попробуйте используя встроенные инструменты Python проанализировать таблицу из файла "Vacancy.csv"
# 3. Попробуйте ответить на вопросы:
# Сколько вакансий, которые вам нравятся?
# Насколько свежие эти вакансии?
# Сколько вакансий с позициями на которых вы работаете?
# Сколько вакансий для аналатика данных?
# Сколько вакансий для аналитика данных с использованием Python?

In [10]:
import csv

In [11]:
import sys

In [58]:
from collections import Counter

In [19]:
#данная конструкция заканчивается ошибкой. Прогуглил на stackoverflow другое решение. Использовал в следующей строке
csv.field_size_limit(sys.maxsize)

OverflowError: Python int too large to convert to C long

In [20]:
maxInt = sys.maxsize

while True:
    try:
        csv.field_size_limit(maxInt)
        break
    except OverflowError:
        maxInt = int(maxInt/10)

In [48]:
# проблему с кодировкой удалось решить с помощью добавления конструкции типа - encoding='utf-8'
# проблему со считыванием файла удалось решить разархивированием файла в исходной папке
vacs = list(csv.DictReader(open('Vacancy.csv', encoding='utf-8')))

In [54]:
len(vacs)

4002

In [71]:
#кроме этого и уточнения длины списка дргуие манипульции стандарнтными функциями Python провести не удалось. Решил далее работать через pd

### Загружаем библиотеки и файл для анализа данных

In [106]:
import pandas as pd
import numpy as np
vacs = pd.read_csv('C:/Users/user/Desktop/ДЗ Reboot/L1/Lesson1/hometask/vacancy.csv')

### Техническое задание

In [109]:
# Сколько вакансий, которые вам нравятся?
# Насколько свежие эти вакансии?
# Сколько вакансий с позициями на которых вы работаете?
# Сколько вакансий для аналатика данных?
# Сколько вакансий для аналитика данных с использованием Python?

### Первичный анализ данных/ Знакомство с датафрейм по кейсу

In [110]:
vacs

,id,created_at,updated_at,vacid,vactitle,vacdescription,vacdate,vacstatus,vaclink,vachtml
0,383479,2021-03-14 09:39:21.854462,2021-03-14 09:39:21.854584,1474941,Senior java-разработчик (в команду Онбординга),"Работа у нас — это:команда профессионалов, го...",2021-03-15,new,https://my.sbertalents.ru/#/job-requisition/14...,"{""title"": ""Senior java-\u0440\u0430\u0437\u044..."
1,383480,2021-03-14 09:39:21.854462,2021-03-14 09:39:21.854584,1476154,Дизайнер мобильных приложений,Мы ищем дизайнера в нашу дружную команду Сбер...,2021-03-15,new,https://my.sbertalents.ru/#/job-requisition/14...,"{""title"": ""\u0414\u0438\u0437\u0430\u0439\u043..."
2,383481,2021-03-14 09:39:21.854462,2021-03-14 09:39:21.854584,1479834,Старший специалист отдела мониторинга залогово...,Условия: ● официальное трудоустройство;● 5-т...,2021-03-15,new,https://my.sbertalents.ru/#/job-requisition/14...,"{""title"": ""\u0421\u0442\u0430\u0440\u0448\u043..."
3,383482,2021-03-14 09:39:21.854462,2021-03-14 09:39:21.854584,1484458,Аналитик/разработчик (Программа 'Миграция Leg...,В Блоке Риски стартовала Программа ‘Миграция L...,2021-03-15,new,https://my.sbertalents.ru/#/job-requisition/14...,"{""title"": ""\u0410\u043d\u0430\u043b\u0438\u044..."
4,383483,2021-03-14 09:39:21.854462,2021-03-14 09:39:21.854584,1489383,Java разработчик (Команда Functions),Работа у нас — это:работа в крупнейшем банке ...,2021-03-15,new,https://my.sbertalents.ru/#/job-requisition/14...,"{""title"": ""Java \u0440\u0430\u0437\u0440\u0430..."
...,...,...,...,...,...,...,...,...,...,...
3997,383474,2021-03-14 09:39:21.854462,2021-03-14 09:39:21.854584,1452160,Руководитель направления (CI/CD),Система статического и динамического анализа и...,2021-03-15,new,https://my.sbertalents.ru/#/job-requisition/14...,"{""title"": ""\u0420\u0443\u043a\u043e\u0432\u043..."
3998,383475,2021-03-14 09:39:21.854462,2021-03-14 09:39:21.854584,1465146,Frontend разработчик (продукт Puzzle),Puzzle – UI аналитика для проведения служебных...,2021-03-15,new,https://my.sbertalents.ru/#/job-requisition/14...,"{""title"": ""Frontend \u0440\u0430\u0437\u0440\u..."
3999,383476,2021-03-14 09:39:21.854462,2021-03-14 09:39:21.854584,1469858,Инженер дежурной смены,Условия:Работа в крупнейшем Центре киберзащит...,2021-03-15,new,https://my.sbertalents.ru/#/job-requisition/14...,"{""title"": ""\u0418\u043d\u0436\u0435\u043d\u043..."
4000,383477,2021-03-14 09:39:21.854462,2021-03-14 09:39:21.854584,1470061,Главный инженер (системы защиты от DDoS-атак),Продукт Защита периметра (защита от DDos-атак ...,2021-03-15,new,https://my.sbertalents.ru/#/job-requisition/14...,"{""title"": ""\u0413\u043b\u0430\u0432\u043d\u044..."
4001,383478,2021-03-14 09:39:21.854462,2021-03-14 09:39:21.854584,1474689,Мобильный менеджер по продажам со знанием тадж...,Мы предлагаем: - оформление согласно трудовому...,2021-03-15,new,https://my.sbertalents.ru/#/job-requisition/14...,"{""title"": ""\u041c\u043e\u0431\u0438\u043b\u044..."

In [111]:
vacs.info()
vacs.describe()
vacs.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4002 entries, 0 to 4001
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              4002 non-null   int64
 1   created_at      4002 non-null   object
 2   updated_at      4002 non-null   object
 3   vacid           4002 non-null   int64
 4   vactitle        4002 non-null   object
 5   vacdescription  3886 non-null   object
 6   vacdate         4000 non-null   object
 7   vacstatus       4002 non-null   object
 8   vaclink         4002 non-null   object
 9   vachtml         4002 non-null   object
dtypes: int64(2), object(8)
memory usage: 312.8+ KB

Index(['id', 'created_at', 'updated_at', 'vacid', 'vactitle', 'vacdescription',
       'vacdate', 'vacstatus', 'vaclink', 'vachtml'],
      dtype='object')

In [112]:
vacs.nunique()

id                4002
created_at           1
updated_at           1
vacid             4002
vactitle          2167
vacdescription    3562
vacdate            115
vacstatus            1
vaclink           4002
vachtml           3790
dtype: int64

In [113]:
#для того чтобы железо обрабатывало меньшее количество данных я удалил столбцы, которые не помогут ответить на вопрос ТЗ или имеют 1 уникальное значение
vacs = vacs.drop(['updated_at', 'vacid', 'vacstatus', 'created_at', 'vaclink', 'vachtml'], axis=1)

In [124]:
vacs

,id,vactitle,vacdescription,vacdate
0,383479,Senior java-разработчик (в команду Онбординга),"Работа у нас — это:команда профессионалов, го...",2021-03-15
1,383480,Дизайнер мобильных приложений,Мы ищем дизайнера в нашу дружную команду Сбер...,2021-03-15
2,383481,Старший специалист отдела мониторинга залогово...,Условия: ● официальное трудоустройство;● 5-т...,2021-03-15
3,383482,Аналитик/разработчик (Программа 'Миграция Leg...,В Блоке Риски стартовала Программа ‘Миграция L...,2021-03-15
4,383483,Java разработчик (Команда Functions),Работа у нас — это:работа в крупнейшем банке ...,2021-03-15
...,...,...,...,...
3997,383474,Руководитель направления (CI/CD),Система статического и динамического анализа и...,2021-03-15
3998,383475,Frontend разработчик (продукт Puzzle),Puzzle – UI аналитика для проведения служебных...,2021-03-15
3999,383476,Инженер дежурной смены,Условия:Работа в крупнейшем Центре киберзащит...,2021-03-15
4000,383477,Главный инженер (системы защиты от DDoS-атак),Продукт Защита периметра (защита от DDos-атак ...,2021-03-15
4001,383478,Мобильный менеджер по продажам со знанием тадж...,Мы предлагаем: - оформление согласно трудовому...,2021-03-15

# Ответы на техническое задание

### 1. Сколько вакансий, которые вам нравятся?

In [ ]:
#Определяем 2 условия 
    1. nice1 - наименование вакансии, которая включает в себя формулировку 'data analyst'
    2. nice2 - описание вакансии, которое включает в себя формулировку 'дружная команда'
#Отфилтровываем датафрейм с использованием 2 указанных условий

In [181]:
nice1 = vacs.vactitle.str.lower().str.contains('data analyst')
nice2 = vacs.vacdescription.str.lower().str.contains('дружная команда')
vacs[nice1 & nice2]

,id,vactitle,vacdescription,vacdate
808,384287,Data Analyst в команду «Отчетность и аналитика»,Условия:Конкурентоспособный уровень дохода (ок...,2021-03-05

Ответ: согласно условию нашлась 1 вакансия.

### 2. Насколько свежие эти вакансии?

In [122]:
vacs.vacdate.nunique()

115

In [123]:
vacs.vacdate.unique()

array(['2021-03-15', '2021-03-12', '2021-03-13', '2021-03-14',
       '2021-03-11', '2021-03-10', nan, '2021-03-09', '2021-03-05',
       '2021-03-07', '2021-03-08', '2021-03-04', '2021-03-03',
       '2021-03-02', '2021-03-01', '2021-02-28', '2021-02-26',
       '2021-02-27', '2021-02-25', '2021-02-24', '2021-02-20',
       '2021-02-23', '2021-02-22', '2021-02-19', '2021-02-18',
       '2021-02-17', '2021-02-16', '2021-02-15', '2021-02-12',
       '2021-02-14', '2021-02-13', '2021-02-11', '2021-02-10',
       '2021-02-09', '2021-02-08', '2021-02-05', '2021-02-07',
       '2021-02-04', '2021-02-03', '2021-02-02', '2021-02-01',
       '2021-01-31', '2021-01-29', '2021-01-28', '2021-01-27',
       '2021-01-26', '2021-01-25', '2021-01-22', '2021-01-23',
       '2021-01-24', '2021-01-21', '2021-01-20', '2021-01-19',
       '2021-01-18', '2021-01-15', '2021-01-14', '2021-01-13',
       '2021-01-12', '2021-01-11', '2021-01-10', '2020-12-31',
       '2020-12-30', '2021-01-08', '2021-01-03', '2020-12-29',
       '2020-12-28', '2020-12-25', '2020-12-24', '2020-12-22',
       '2020-12-21', '2020-12-18', '2020-12-17', '2020-12-15',
       '2020-12-16', '2020-12-14', '2020-12-11', '2020-12-10',
       '2020-12-09', '2020-12-08', '2020-12-04', '2020-12-07',
       '2020-12-03', '2020-12-02', '2020-12-01', '2020-11-30',
       '2020-11-26', '2020-11-27', '2020-11-24', '2020-11-25',
       '2020-11-23', '2020-11-20', '2020-11-17', '2020-11-19',
       '2020-11-18', '2020-11-16', '2020-11-13', '2020-11-12',
       '2020-11-11', '2020-11-10', '2020-11-09', '2020-11-06',
       '2020-11-05', '2020-11-02', '2020-10-30', '2020-10-28',
       '2020-10-29', '2020-10-27', '2020-10-23', '2020-10-26',
       '2020-10-21', '2020-10-19', '2020-10-20', '2020-10-15',
       '2020-10-16', '2021-03-17', '2021-03-16'], dtype=object)

In [121]:
vacs.sort_values(by='vacdate')

,id,vactitle,vacdescription,vacdate
3503,386982,Координатор тестовых стендов,"Компания «Сбербанк», блок Технологии, сейчас в...",2020-10-15
3502,386981,Старший специалист по взысканию,Условия: работа в крупнейшем банке России;труд...,2020-10-15
3499,386978,Специалист по работе с клиентами (call-центр),Мы готовы предложить тебе:корпоративное обучен...,2020-10-15
3504,386983,"Senior Data analyst (блок УБ, команда инвестиц...",Условия: Современный IT-офис вблизи м. Кутузов...,2020-10-16
3500,386979,Data scientist (NLP) - Sberbank AI Lab,Условия: • Дружный и высококвалифицированны...,2020-10-16
...,...,...,...,...
3625,383102,Ведущий инженер по сопровождению,NaN,2021-03-17
3635,383112,Главный аналитик,Мобильное рабочее место руководителя и сот...,2021-03-17
3510,382987,Клиентский менеджер Сбербанк Первый,Условия:- работа в крупнейшем банке Рос...,2021-03-17
535,384014,Системный аналитик (платформа рекомендаций),"Полный рабочий день, свободный графикДостойна...",NaN
729,384208,Главный инженер по сопровождению Департамента ...,Условия Достойная зработная плата (оклад + пре...,NaN

Ответ: 
    - самая первая вакансия от 15.10.2020
    - самая свежая вакансия от 17.03.2021

### 3. Сколько вакансий с позициями на которых вы работаете?

In [ ]:
#Определяем условие 
    1. nice1 - наименование вакансии, которая включает в себя формулировку 'руководитель проектов'
#Отфилтровываем датафрейм с использованием указанного условия
#В данном кейсе мы не учитываем пустые значения в столбце vacdate

In [183]:
nice1 = vacs.vactitle.str.lower().str.contains('руководитель проектов')
vacs[nice1]

,id,vactitle,vacdescription,vacdate
26,383505,Руководитель проектов,"Задачи:Управлять работой команды, вне зависимо...",2021-03-15
523,384002,Руководитель проектов дирекции по развитию кор...,Условия: работа в крупнейшем банке России;труд...,2021-03-10
552,384031,Руководитель проектов маркетинговых активностей,Условия:работа в крупнейшем банке России;трудо...,2021-03-10
1466,384945,Руководитель проектов,Обязанности: Определяет цели agile-команды и с...,2021-03-01
2133,385612,Руководитель проектов аутентификации в КЦ,УсловияПолный рабочий деньДостойная зработная ...,2021-02-16
2265,385744,"Руководитель проектов (Кластер ""Управление цен...",Мы - это Кластер Управление ценой и доходность...,2021-02-12
2432,385911,Руководитель проектов,"Условия:ЦА, Блок Управление благоcостоянием, Ц...",2021-02-08
2511,385990,"Руководитель проектов, сегмент ""Иностранцы""",Условия:Работа в команде самого большого бан...,2021-02-05
2618,386097,Руководитель проектов по стратегическим партнё...,"Условия работы:Оформление в ЦА ПАО Сбербанк,Бе...",2021-02-02
2655,386134,Лидер внедрения государственных суперсервисов ...,"Условия:• Работа в команде профессионалов, ...",2021-02-01
2679,386158,Руководитель проектов,Команда Solution ТAM’s (technical account mana...,2021-02-01
2705,386184,Руководитель проектов,Задачи:Проектирование моделей процессов в сред...,2021-01-31
2879,386358,Руководитель проектов по сопровождению внешних...,Условия:Современный офис A класса (AgileHome)...,2021-01-25
2983,386462,Руководитель проектов по аналитике,Условия:Конкурентоспособный уровень дохода (ок...,2021-01-19
3121,386600,Руководитель проектов Agile,В основные обязанности входит:Развитие методол...,2021-01-12

In [ ]:
#так как значения в столбце id уникальны для всех 4002 строк всего датафрейм, посчитаем сколько значений у нас после фильтрации

In [185]:
vacs[nice1].id.count()

15

Ответ: согласно условию нашлось 15 вакансий для руководителя проектов.

### 4. Сколько вакансий для аналатика данных?

In [ ]:
#Определяем условие 
    1. nice1 - наименование вакансии, которая включает в себя формулировку data analyst
#Отфилтровываем датафрейм с использованием указанного условия
#В данном кейсе мы не учитываем пустые значения в столбце vacdate

In [162]:
nice1 = vacs.vactitle.str.lower().str.contains('data analyst')
vacs[nice1]

,id,vactitle,vacdescription,vacdate
221,383700,Data analyst. Аналитик данных в трайб «Массова...,Обязанности:- анализ данных по процессам взаим...,2021-03-12
808,384287,Data Analyst в команду «Отчетность и аналитика»,Условия:Конкурентоспособный уровень дохода (ок...,2021-03-05
1051,384530,Data Analyst,"Условия:Профессиональное обучение, семинары, ...",2021-03-03
1230,384709,Data analyst (Python),Мы предлагаем: Конкурентную заработную платуУ...,2021-03-02
1759,385238,Data Analyst Дивизион `Массовая персонализация`,Условия:Современный IT-офис вблизи Москва-Сити...,2021-02-24
2226,385705,Data analyst,Требования:Высшее техническое образованиеУвере...,2021-02-12
2321,385800,Руководитель направления по аналитике данных в...,В связи с ростом команды ведем поиск Data Anal...,2021-02-10
2534,386013,Data Analyst,Мы ищем специалистов в работе с данными. Преим...,2021-02-04
2664,386143,Data analyst (внедрение моделей),Условия:· Достойный уровень оплаты тр...,2021-02-02
2814,386293,Data Analyst,"Условия: Профессиональное обучение, семинары, ...",2021-01-27
2848,386327,Стажер Data engineer/Data analyst,В поиске стажера data аналитика/data инженера ...,2021-01-25
2866,386345,Data analyst (в Лабораторию клиентского опыта),Условия:Работа в крупнейшем банке России. Тр...,2021-01-22
2884,386363,Data analyst (Казначейство),Для реализации стратегически значимого проекта...,2021-01-25
2905,386384,Data analyst,Мы ценим своих сотрудников и предлагаем:Курсы ...,2021-01-22
2919,386398,Data analyst. Стажера - Аналитик (кластер Перс...,В рамках стажировки ты будешь заниматься анали...,2021-01-21
2948,386427,Lead Data Analyst,Мы предлагаем: масштабные и высоконагруженные...,2021-01-20
3103,386582,"Data Analyst Дивизион ""Особенные решения""","В Дивизионе ""Особенные Решения"" Кластера ""Анал...",2021-01-12
3405,386884,Аналитик / data analyst. Дивизион `Лояльность`,Обязанности Лидирование аналитической функции ...,2020-12-04
3407,386886,Senior data analyst. Дивизион `Лояльность`,Обязанности Лидирование аналитической функции ...,2020-12-04
3455,386934,Senior Data Analyst,"Условия:Интересные и масштабные задачи, интелл...",2020-11-17
3489,386968,"Data Analyst (""Корпоративные клиенты 360"")",Условия:Хорошо мотивирующий оклад + система пр...,2020-10-23
3504,386983,"Senior Data analyst (блок УБ, команда инвестиц...",Условия: Современный IT-офис вблизи м. Кутузов...,2020-10-16

In [ ]:
#так как значения в столбце id уникальны для всех 4002 строк всего датафрейм, посчитаем сколько значений у нас после фильтрации

In [164]:
vacs[nice1].id.count()

22

Ответ: согласно условию нашлось 22 вакансии для аналитика данных.

### 5. Сколько вакансий для аналитика данных с использованием Python?

In [ ]:
#Определяем 2 условия 
    1. nice1 - наименование вакансии, которая включает в себя формулировку data analyst
    2. nice2 - описание вакансии, которое включает в себя слово python
#Отфилтровываем датафрейм с использованием 2 указанных условий
#В данном кейсе мы не учитываем пустые значения в столбце vacdate

In [157]:
nice1 = vacs.vactitle.str.lower().str.contains('data analyst')
nice2 = vacs.vacdescription.str.lower().str.contains('python')
vacs[nice1 & nice2]

,id,vactitle,vacdescription,vacdate
221,383700,Data analyst. Аналитик данных в трайб «Массова...,Обязанности:- анализ данных по процессам взаим...,2021-03-12
808,384287,Data Analyst в команду «Отчетность и аналитика»,Условия:Конкурентоспособный уровень дохода (ок...,2021-03-05
1051,384530,Data Analyst,"Условия:Профессиональное обучение, семинары, ...",2021-03-03
1230,384709,Data analyst (Python),Мы предлагаем: Конкурентную заработную платуУ...,2021-03-02
1759,385238,Data Analyst Дивизион `Массовая персонализация`,Условия:Современный IT-офис вблизи Москва-Сити...,2021-02-24
2534,386013,Data Analyst,Мы ищем специалистов в работе с данными. Преим...,2021-02-04
2664,386143,Data analyst (внедрение моделей),Условия:· Достойный уровень оплаты тр...,2021-02-02
2814,386293,Data Analyst,"Условия: Профессиональное обучение, семинары, ...",2021-01-27
2919,386398,Data analyst. Стажера - Аналитик (кластер Перс...,В рамках стажировки ты будешь заниматься анали...,2021-01-21
2948,386427,Lead Data Analyst,Мы предлагаем: масштабные и высоконагруженные...,2021-01-20
3103,386582,"Data Analyst Дивизион ""Особенные решения""","В Дивизионе ""Особенные Решения"" Кластера ""Анал...",2021-01-12
3405,386884,Аналитик / data analyst. Дивизион `Лояльность`,Обязанности Лидирование аналитической функции ...,2020-12-04
3407,386886,Senior data analyst. Дивизион `Лояльность`,Обязанности Лидирование аналитической функции ...,2020-12-04
3455,386934,Senior Data Analyst,"Условия:Интересные и масштабные задачи, интелл...",2020-11-17
3489,386968,"Data Analyst (""Корпоративные клиенты 360"")",Условия:Хорошо мотивирующий оклад + система пр...,2020-10-23
3504,386983,"Senior Data analyst (блок УБ, команда инвестиц...",Условия: Современный IT-офис вблизи м. Кутузов...,2020-10-16

In [ ]:
#так как значения в столбце id уникальны для всех 4002 строк всего датафрейм, посчитаем сколько значений у нас после фильтрации

In [159]:
vacs[nice1 & nice2].id.count()

16

Ответ: согласно условию нашлось 16 вакансий для аналитика данных с использованием Python.